import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..", "..");
const html = readFileSync(join(ROOT, "index.html"), "utf8");

/** PNG width/height live at a fixed offset in the IHDR chunk. */
const pngSize = (name) => {
  const b = readFileSync(join(ROOT, "public", name));
  return { w: b.readUInt32BE(16), h: b.readUInt32BE(20) };
};

/**
 * THE BRAND ASSETS GOOGLE ACTUALLY READS.
 *
 * A search result that shows a generic globe instead of a mark reads as a
 * site nobody owns, and that is what this domain looked like. The cause was
 * not a missing file — favicon.png existed and was linked. It was 128x128.
 *
 * Google only considers a favicon whose dimensions are a SQUARE MULTIPLE OF
 * 48. 128 is not one, so it was discarded silently: nothing 404s, nothing
 * warns, the row just falls back. That is the kind of rule that gets
 * re-broken by whoever next thinks a power of two looks tidier, which is why
 * it is asserted here rather than only explained in a comment.
 *
 * These are generated by scripts/render-og.mjs. This file checks the OUTPUT
 * and the markup agree, because the two drifting apart is invisible until it
 * shows up in a search result weeks later.
 */
describe("brand assets", () => {
  it("the favicon is a square multiple of 48, which is Google's rule", () => {
    const { w, h } = pngSize("favicon.png");
    expect(w).toBe(h);
    expect(w % 48).toBe(0);
  });

  it("index.html declares the size the file actually is", () => {
    const { w } = pngSize("favicon.png");
    expect(html).toContain(`href="/favicon.png" type="image/png" sizes="${w}x${w}"`);
  });

  /**
   * logo.png is a #040404 square with the mark drawn nearly black inside it.
   * Anywhere it is composited on white — a search result, a home screen — it
   * is a black tile. Every outward-facing reference must use the keyed mark
   * on its own tile instead.
   */
  it("nothing outward-facing points at the black-on-black logo.png", () => {
    expect(existsSync(join(ROOT, "public", "logo-mark.png"))).toBe(true);
    expect(html).toContain('"logo": "https://alop-ai.com/logo-mark.png"');
    expect(html).not.toContain('rel="apple-touch-icon" href="/logo.png"');
  });

  it("the social card is the size every platform crops to", () => {
    expect(pngSize("og.png")).toEqual({ w: 1200, h: 630 });
    expect(html).toContain('content="1200"');
    expect(html).toContain('content="630"');
  });
});
